In [33]:
# importing required libraries 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [34]:
# reading csv file and extracting class column to y. 
forestfires = pd.read_csv("~/Downloads/Data Science/data set/forestfires.csv")
forestfires

,Unnamed: 0,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,1,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,...,0,0,0,0,1,0,0,0,0,small
1,2,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,...,0,0,0,0,0,0,0,1,0,small
2,3,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,...,0,0,0,0,0,0,0,1,0,small
3,4,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,...,0,0,0,0,1,0,0,0,0,small
4,5,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,...,0,0,0,0,1,0,0,0,0,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,513,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,...,0,0,0,0,0,0,0,0,0,large
513,514,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,...,0,0,0,0,0,0,0,0,0,large
514,515,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,...,0,0,0,0,0,0,0,0,0,large
515,516,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,...,0,0,0,0,0,0,0,0,0,small
516,517,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,...,0,0,0,0,0,0,1,0,0,small

In [35]:
#drop unnecessary columan
forestfires.drop(['month','day','Unnamed: 0'], axis=1, inplace=True)

In [36]:
#feture selection
y = forestfires.size_category
forestfires.drop(['size_category'], axis=1, inplace=True)
X = forestfires

In [37]:
#convert category to int
y.replace('small',0,regex=True, inplace = True)
y.replace('large',1,regex=True, inplace = True)

In [38]:
#Splitting Data

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,random_state=109)

In [39]:
from sklearn import svm
#create a classifier
cls = svm.SVC(kernel="linear")
#train the model
cls.fit(X_train,y_train)
#predict the response
pred = cls.predict(X_test)

In [40]:
#Evaluating the Model
from sklearn import metrics
#accuracy
print("acuracy:", metrics.accuracy_score(y_test,y_pred=pred))
#precision score
print("precision:", metrics.precision_score(y_test,y_pred=pred))
#recall score
print("recall" , metrics.recall_score(y_test,y_pred=pred))
print(metrics.classification_report(y_test, y_pred=pred))

acuracy: 1.0
precision: 1.0
recall 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00        57

    accuracy                           1.00       207
   macro avg       1.00      1.00      1.00       207
weighted avg       1.00      1.00      1.00       207